name: $(Date:yyyyMMdd).$(Rev:.r)
pr:
  branches:
    include:
    - develop
  paths:
    exclude:
    - README.md
    - changelog.md
    - compatibility.md
    - publishing
trigger: none
jobs:
- job:
  displayName: Running URLDuplicatesQuick test on MS agent
  pool:
    name: Hosted
    vmImage: win1803
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/URLDuplicatesQuick.ps1
    displayName: URLDuplicatesQuick
    errorActionPreference: continue
- job:
  displayName: Running ValidUrls test on MS agent
  pool:
    name: Hosted
    vmImage: win1803
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ValidUrls.ps1
    displayName: ValidUrls
    errorActionPreference: continue
- job:
  displayName: Running Extract test on MS agent
  pool:
    name: Hosted
    vmImage: win1803
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/extract.ps1
    displayName: extract
    errorActionPreference: continue
#- job:
#  displayName: Running ChecksumVerification on a self hosted agent
#  pool: Default
#  timeoutInMinutes: 2880
#  steps:
#  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification.ps1
#    displayName: ChecksumVerification
#    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 00
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification00.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 01
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification01.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 02
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification02.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 03
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification03.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 04
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification04.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 05
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification05.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 06
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification06.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 07
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification07.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 08
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification08.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 09
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification09.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 10
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification10.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 11
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification11.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 12
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification12.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 13
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification13.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 14
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification14.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 15
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification15.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 16
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification16.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 17
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification17.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 18
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification18.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 19
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 600
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification19.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running role installation tests on a self hosted agent
  pool: Default
  timeoutInMinutes: 1440
  steps:
  - powershell: cd ci; ./booknode.ps1
    displayName: Booking the hypervisor node
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd tests; kitchen destroy;
    displayName: Cleaning up the kitchen
    errorActionPreference: continue
#  - powershell: cd tests; kitchen test InstallAllPrerequisitesLocal-win2019-basic;
#    displayName: kitchen test InstallAllPrerequisitesLocal-win2019-basic
#    errorActionPreference: continue
  - powershell: cd infrastructure/images; ./preparevmimages.ps1 win2016-sql2016dbrs,win2016-ad,win2019-soe,win2016-soe
    displayName: Building images
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-sql2016dbrs *" } ) ) { exit 1 }
    displayName: Checking the win2016-sql2016dbrs image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-ad *" } ) ) { exit 1 }
    displayName: Checking the win2016-ad image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2019-soe *" } ) ) { exit 1 }
    displayName: Checking the win2019-soe image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-soe *" } ) ) { exit 1 }
    displayName: Checking the win2016-soe image
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; ..\localdeploy.ps1;
    displayName: Spinning up service VMs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test RoleAddition-win2019-dynamicsprereqs;
    displayName: kitchen test RoleAddition-win2019-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test RoleJoining-win2016-dynamicsprereqs;
    displayName: kitchen test RoleJoining-win2016-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd ci;./releasenode.ps1
    #condition: always()
    displayName: Releasing the hypervisor node booking
    errorActionPreference: continue
- job:
  displayName: Running Quick 9.0 tests on a self hosted agent
  pool: Default
  timeoutInMinutes: 1440
  steps:
  - powershell: cd ci; ./booknode.ps1
    displayName: Booking the hypervisor node
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd tests; kitchen destroy;
    displayName: Cleaning up the kitchen
    errorActionPreference: continue
#  - powershell: cd tests; kitchen test InstallAllPrerequisitesLocal-win2019-basic;
#    displayName: kitchen test InstallAllPrerequisitesLocal-win2019-basic
#    errorActionPreference: continue
  - powershell: cd infrastructure/images; ./preparevmimages.ps1 win2016-sql2016dbrs,win2016-ad,win2019-soe
    displayName: Building images
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-sql2016dbrs *" } ) ) { exit 1 }
    displayName: Checking the win2016-sql2016dbrs image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-ad *" } ) ) { exit 1 }
    displayName: Checking the win2016-ad image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2019-soe *" } ) ) { exit 1 }
    displayName: Checking the win2019-soe image
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; ..\localdeploy.ps1;
    displayName: Spinning up service VMs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test QuickProvisioning-win2019-dynamicsprereqs;
    displayName: kitchen test QuickProvisioning-win2019-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd ci;./releasenode.ps1
    #condition: always()
    displayName: Releasing the hypervisor node booking
    errorActionPreference: continue
- job:
  displayName: Running Quick 2016 tests on a self hosted agent
  pool: Default
  timeoutInMinutes: 1440
  steps:
  - powershell: cd ci; ./booknode.ps1
    displayName: Booking the hypervisor node
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd tests; kitchen destroy;
    displayName: Cleaning up the kitchen
    errorActionPreference: continue
#  - powershell: cd tests; kitchen test InstallAllPrerequisitesLocal-win2019-basic;
#    displayName: kitchen test InstallAllPrerequisitesLocal-win2019-basic
#    errorActionPreference: continue
  - powershell: cd infrastructure/images; ./preparevmimages.ps1 win2016-sql2016dbrs,win2016-ad,win2016-soe
    displayName: Building images
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-sql2016dbrs *" } ) ) { exit 1 }
    displayName: Checking the win2016-sql2016dbrs image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-ad *" } ) ) { exit 1 }
    displayName: Checking the win2016-ad image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-soe *" } ) ) { exit 1 }
    displayName: Checking the win2016-soe image
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; ..\localdeploy.ps1;
    displayName: Spinning up service VMs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test QuickProvisioning2016-win2016-dynamicsprereqs;
    displayName: kitchen test QuickProvisioning2016-win2016-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd ci;./releasenode.ps1
    #condition: always()
    displayName: Releasing the hypervisor node booking
    errorActionPreference: continue
- job:
  displayName: Running Full 9.0 tests on a self hosted agent
  pool: Default
  timeoutInMinutes: 1440
  steps:
  - powershell: cd ci; ./booknode.ps1
    displayName: Booking the hypervisor node
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd tests; kitchen destroy;
    displayName: Cleaning up the kitchen
    errorActionPreference: continue
#  - powershell: cd tests; kitchen test InstallAllPrerequisitesLocal-win2019-basic;
#    displayName: kitchen test InstallAllPrerequisitesLocal-win2019-basic
#    errorActionPreference: continue
  - powershell: cd infrastructure/images; ./preparevmimages.ps1 win2016-sql2016dbrs,win2016-ad
    displayName: Building images
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-sql2016dbrs *" } ) ) { exit 1 }
    displayName: Checking the win2016-sql2016dbrs image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-ad *" } ) ) { exit 1 }
    displayName: Checking the win2016-ad image
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant up AD01;
    displayName: Spinning up service VMs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test Provision90Full-win2016-sql2016dbrs-dynamicsprereqs;
    displayName: kitchen test Provision90Full-win2016-sql2016dbrs-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd ci;./releasenode.ps1
    #condition: always()
    displayName: Releasing the hypervisor node booking
    errorActionPreference: continue
- job:
  displayName: Running Full 2016 tests on a self hosted agent
  pool: Default
  timeoutInMinutes: 1440
  steps:
  - powershell: cd ci; ./booknode.ps1
    displayName: Booking the hypervisor node
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant suspend;
    displayName: Suspending the stack
    errorActionPreference: continue
#  - powershell: cd tests; kitchen test InstallAllPrerequisitesLocal-win2019-basic;
#    displayName: kitchen test InstallAllPrerequisitesLocal-win2019-basic
#    errorActionPreference: continue
  - powershell: cd infrastructure/images; ./preparevmimages.ps1 win2012r2-ad-sql2016dbrs
    displayName: Building images
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2012r2-ad-sql2016dbrs *" } ) ) { exit 1 }
    displayName: Checking the win2012r2-ad-sql2016dbrs image
    errorActionPreference: continue
  - powershell: cd tests; kitchen test Provision2016Full-win2012r2-ad-sql2016dbrs-dynamicsprereqs;
    displayName: kitchen test Provision2016Full-win2012r2-ad-sql2016dbrs-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd ci;./releasenode.ps1
    #condition: always()
    displayName: Releasing the hypervisor node booking
    errorActionPreference: continue
