name: $(Date:yyyyMMdd).$(Rev:.r)
pr:
  branches:
    include:
    - develop
  paths:
    exclude:
    - README.md
    - changelog.md
    - compatibility.md
    - publishing
trigger: none
jobs:
- job:
  displayName: Running URLDuplicatesQuick test on MS agent
  pool:
    name: Hosted
    vmImage: win1803
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/URLDuplicatesQuick.ps1
    displayName: URLDuplicatesQuick
    errorActionPreference: continue
- job:
  displayName: Running ValidUrls test on MS agent
  pool:
    name: Hosted
    vmImage: win1803
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ValidUrls.ps1
    displayName: ValidUrls
    errorActionPreference: continue
- job:
  displayName: Running Extract test on MS agent
  pool:
    name: Hosted
    vmImage: win1803
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/extract.ps1
    displayName: extract
    errorActionPreference: continue
#- job:
#  displayName: Running ChecksumVerification on a self hosted agent
#  pool: Default
#  timeoutInMinutes: 2880
#  steps:
#  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification.ps1
#    displayName: ChecksumVerification
#    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 0
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification0.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 1
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification1.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 2
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification2.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 3
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification3.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 4
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification4.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 5
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification5.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 6
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification6.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 7
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification7.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 8
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification8.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running ChecksumVerification on MS agent 9
  pool:
    name: Hosted
    vmImage: win1803
  timeoutInMinutes: 2880
  steps:
  - powershell: Import-Module ./src/Dynamics365Configuration/Dynamics365Configuration.psd1; ./tests/ChecksumVerification9.ps1
    displayName: ChecksumVerification
    errorActionPreference: continue
- job:
  displayName: Running integration tests on a self hosted agent
  pool: Default
  timeoutInMinutes: 1440
  steps:
  - powershell: cd ci; ./booknode.ps1
    displayName: Booking the hypervisor node
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd tests; kitchen destroy;
    displayName: Cleaning up the kitchen
    errorActionPreference: continue
  - powershell: cd tests; kitchen test InstallAllPrerequisitesLocal-win2019-basic;
    displayName: kitchen test InstallAllPrerequisitesLocal-win2019-basic
    errorActionPreference: continue
#  - powershell: cd tests; kitchen test ValidUrls-win2012r2-basic;
#    displayName: kitchen test ValidUrls-win2012r2-basic
#    errorActionPreference: continue
  - powershell: cd infrastructure/images; ./preparevmimages.ps1 win2016-sql2016dbrs,win2012r2-ad-sql2016dbrs,win2016-ad,win2019-soe,win2016-soe
    displayName: Building images
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-sql2016dbrs *" } ) ) { exit 1 }
    displayName: Checking the win2016-sql2016dbrs image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2012r2-ad-sql2016dbrs *" } ) ) { exit 1 }
    displayName: Checking the win2012r2-ad-sql2016dbrs image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-ad *" } ) ) { exit 1 }
    displayName: Checking the win2016-ad image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2019-soe *" } ) ) { exit 1 }
    displayName: Checking the win2019-soe image
    errorActionPreference: continue
  - powershell: if ( !( vagrant box list | ? { $_ -like "win2016-soe *" } ) ) { exit 1 }
    displayName: Checking the win2016-soe image
    errorActionPreference: continue
  #- powershell: cd tests; kitchen test SaveAllResources-win2016-soe;
  #  displayName: kitchen test SaveAllResources-win2016-soe
  #  errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; ..\localdeploy.ps1;
    displayName: Spinning up service VMs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test RoleInstallation-win2019-dynamicsprereqs;
    displayName: kitchen test RoleInstallation-win2019-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test RoleJoining-win2016-dynamicsprereqs;
    displayName: kitchen test Provision90Full-win2016-sql2016dbrs-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; ..\localdeploy.ps1;
    displayName: Spinning up service VMs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test QuickProvisioning-win2019-dynamicsprereqs;
    displayName: kitchen test QuickProvisioning-win2019-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; ..\localdeploy.ps1;
    displayName: Spinning up service VMs
    errorActionPreference: continue
  - powershell: cd tests; kitchen test QuickProvisioning2016-win2016-dynamicsprereqs;
    displayName: kitchen test QuickProvisioning2016-win2016-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant destroy DB01 --force;
    displayName: Cleaning up the stack
    errorActionPreference: continue
  - powershell: cd tests; kitchen test Provision90Full-win2016-sql2016dbrs-dynamicsprereqs;
    displayName: kitchen test Provision90Full-win2016-sql2016dbrs-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd infrastructure/stacks/kitchenci-ad-sql2016dbrs; vagrant suspend;
    displayName: Suspending the stack
    errorActionPreference: continue
  - powershell: cd tests; kitchen test Provision2016Full-win2012r2-ad-sql2016dbrs-dynamicsprereqs;
    displayName: kitchen test Provision2016Full-win2012r2-ad-sql2016dbrs-dynamicsprereqs
    errorActionPreference: continue
  - powershell: cd ci;./releasenode.ps1
    #condition: always()
    displayName: Releasing the hypervisor node booking
    errorActionPreference: continue
