name: $(Date:yyyyMMdd).$(Rev:.r)
pr:
- release-*
trigger:
  branches:
    include:
    - release-*
    exclude:
    - develop

variables:
  NuGetApiKey: 'put-the-key-here'

jobs:
- job:
  displayName: Relesing the module
  pool:
    name: Hosted
    vmImage: windows-2019
  steps:
  - powershell: ./publishing/psmodulepublishing.ps1
    displayName: Releasing the module
    errorActionPreference: continue
