name: $(Date:yyyyMMdd).$(Rev:.r)
pr:
- release-*
trigger:
  branches:
    include:
    - release-*
    exclude:
    - develop

jobs:
- job:
  displayName: Releasing the module
  pool:
    name: Hosted
    vmImage: windows-2019
  steps:
  - task: NuGetToolInstaller@1    
  - powershell: ./publishing/psmodulepublishing.ps1
    displayName: Releasing the module
    env:
      NuGetApiKey: $(NuGetApiKey)
